"use client";

import Link from "next/link";
import { useMemo, useState, useTransition, type CSSProperties } from "react";
import { useRouter } from "next/navigation";
import { applyMealTemplate, deleteDynamicMeal, saveDayAsTemplate, saveDynamicMeal } from "../dynamic-actions";
import { mealTotals, type DynamicMeal, type DynamicMealDraft, type DynamicMealDraftItem, type DynamicNutritionData } from "../dynamic-types";
import type { NutritionGoals } from "../types";
import styles from "./dynamic-nutrition.module.css";

const round = (value: number) => Math.round(value * 10) / 10;
const dateShift = (date: string, days: number) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); };
const emptyMeal = (date: string): DynamicMealDraft => ({ id: crypto.randomUUID(), date, name: "", plannedTime: "", items: [] });

export function DynamicNutritionPlanner({ date, data, goals, openNew = false }: { date: string; data: DynamicNutritionData; goals: NutritionGoals; openNew?: boolean }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [draft, setDraft] = useState<DynamicMealDraft | null>(() => openNew ? emptyMeal(date) : null); const [message, setMessage] = useState("");
  const [templateName, setTemplateName] = useState("");
  const [showTemplateSave, setShowTemplateSave] = useState(false);
  const choices = useMemo(() => [...data.products.map((item) => ({ type: "product" as const, id: item.id, label: item.name })), ...data.recipes.map((item) => ({ type: "recipe" as const, id: item.id, label: `Рецепта: ${item.name}` }))], [data.products, data.recipes]);
  const totals = data.meals.reduce((sum, meal) => { const value = mealTotals(meal); sum.calories += value.calories; sum.protein += value.protein; sum.carbs += value.carbs; sum.fat += value.fat; return sum; }, { calories: 0, protein: 0, carbs: 0, fat: 0 });
  const reusableMeals = data.meals.filter((meal) => !meal.legacyPayload);
  const calorieProgress = Math.min(100, Math.max(0, totals.calories / Math.max(goals.calories, 1) * 100));
  const plannedProducts = new Set(data.meals.flatMap((meal) => meal.items.map((item) => item.label))).size;
  const openMeal = (meal?: DynamicMeal) => setDraft(meal ? { id: meal.id, date, name: meal.name, plannedTime: meal.plannedTime ?? "", items: meal.items.map((item) => ({ id: item.id, itemType: item.itemType, referenceId: item.productId ?? item.recipeId ?? "", quantity: item.quantity })) } : emptyMeal(date));
  const addItem = () => setDraft((current) => current && choices.length ? { ...current, items: [...current.items, { id: crypto.randomUUID(), itemType: choices[0].type, referenceId: choices[0].id, quantity: choices[0].type === "product" ? 100 : 1 }] } : current);
  const updateItem = (index: number, patch: Partial<DynamicMealDraftItem>) => setDraft((current) => current ? { ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) } : current);
  const run = (action: () => Promise<{ ok: boolean; message: string }>, close = false) => startTransition(async () => { setMessage("Запазване…"); const result = await action(); setMessage(result.message); if (result.ok) { if (close) setDraft(null); router.refresh(); } });
  const persist = () => draft && run(async () => saveDynamicMeal(draft), true);
  const remove = (meal: DynamicMeal) => { if (window.confirm(`Да изтрия ли „${meal.name}“?`)) run(() => deleteDynamicMeal(meal.id)); };
  const apply = (templateId: string, name: string) => { if (window.confirm(`Да заменя ${data.meals.length ? `текущите ${data.meals.length} хранения` : "празния ден"} с шаблон „${name}“?`)) run(() => applyMealTemplate(templateId, date)); };
  const saveTemplate = () => startTransition(async () => { setMessage("Запазване…"); const result = await saveDayAsTemplate(date, templateName); setMessage(result.message); if (result.ok) { setTemplateName(""); setShowTemplateSave(false); router.refresh(); } });

  return <section className={styles.planner}>
    <section className={styles.dayHeader}><div className={styles.toolbar}><div><p className="life-kicker">Дневен план</p><h2>{new Date(`${date}T00:00:00Z`).toLocaleDateString("bg-BG", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" })}</h2></div><button className="primary-button" type="button" onClick={() => openMeal()}>+ Добави хранене</button></div>
    <nav className={styles.dateNav} aria-label="Смяна на ден"><Link href={`/nutrition?date=${dateShift(date, -1)}`} aria-label="Предишен ден">‹</Link><Link href="/nutrition">Днес</Link><Link href={`/nutrition?date=${dateShift(date, 1)}`} aria-label="Следващ ден">›</Link></nav></section>
    <section className={styles.summary} aria-label="Дневен хранителен прием"><div className={styles.calorieRing} style={{ "--progress": `${calorieProgress * 3.6}deg` } as CSSProperties}><span><b>{round(totals.calories)}</b><small>от {goals.calories} kcal</small></span></div><div className={styles.macroList}><span><strong>Протеин</strong><em>{round(totals.protein)} / {goals.protein} g</em><i><b style={{ width: `${Math.min(100, totals.protein / Math.max(goals.protein, 1) * 100)}%` }}/></i></span><span><strong>Въглехидрати</strong><em>{round(totals.carbs)} / {goals.carbs} g</em><i><b style={{ width: `${Math.min(100, totals.carbs / Math.max(goals.carbs, 1) * 100)}%` }}/></i></span><span><strong>Мазнини</strong><em>{round(totals.fat)} / {goals.fat} g</em><i><b style={{ width: `${Math.min(100, totals.fat / Math.max(goals.fat, 1) * 100)}%` }}/></i></span></div></section>
    {message ? <p className={styles.message} role="status">{message}</p> : null}
    <section className={styles.mealsSection}><header><div><p className="life-kicker">За деня</p><h2>Хранения</h2></div><span>{data.meals.length} общо</span></header><div className={styles.list}>{data.meals.map((meal) => { const value = mealTotals(meal); const captured = meal.legacyPayload?.source === "food_photo"; const description = typeof meal.legacyPayload?.description === "string" ? meal.legacyPayload.description : ""; const capturedItems = Array.isArray(meal.legacyPayload?.items) ? meal.legacyPayload.items as Array<{ name?: string; grams?: number; calories?: number }> : []; return <article className={styles.meal} key={meal.id}><header><div><h2>{meal.name}</h2><span>{meal.plannedTime || (captured ? "Добавено от снимка" : "Без час")}</span></div><b>{round(value.calories)} kcal</b></header>{captured && capturedItems.length ? <div className={styles.items}>{capturedItems.map((item, index) => <div className={styles.item} key={`${meal.id}:${index}`}><span><b>{item.name || "Продукт"}</b><br/><small>{round(Number(item.grams) || 0)} g</small></span><b>{round(Number(item.calories) || 0)} kcal</b></div>)}</div> : meal.legacyPayload ? <p className={styles.snapshot}>{description || "Запазено хранене без подробни съставки."}</p> : <div className={styles.items}>{meal.items.map((item) => <div className={styles.item} key={item.id}><span><b>{item.label}</b><br /><small>{item.quantity} {item.unit}</small></span><b>{round(item.calories)} kcal</b></div>)}</div>}<footer><span>П {round(value.protein)} · В {round(value.carbs)} · М {round(value.fat)}</span><div className={styles.mealActions}>{!meal.legacyPayload ? <button type="button" onClick={() => openMeal(meal)}>Редактирай</button> : null}<button type="button" onClick={() => remove(meal)}>Изтрий</button></div></footer></article>; })}{!data.meals.length ? <div className={styles.empty}><strong>Денят е празен</strong><span>Добави хранене от продукти и рецепти или използвай готов шаблон.</span><button type="button" onClick={() => openMeal()}>+ Добави хранене</button></div> : null}</div></section>
    <section className={styles.library}><header><div><p className="life-kicker">Библиотека</p><h2>Запази работещото</h2></div><div className={styles.libraryLinks}><Link href="/recipes">Рецепти <b>{data.recipes.length}</b></Link><Link href="/products">Продукти <b>{data.products.length}</b></Link></div></header><div className={styles.templateHeading}><div><h3>Шаблони за ден</h3><p>Приложи готов план или запази днешния.</p></div><button type="button" onClick={() => setShowTemplateSave(true)}>+ Запази план</button></div>{data.templates.length ? <div className={styles.templates}>{data.templates.map((template) => <article key={template.id}><div><strong>{template.name}</strong><span>{template.mealCount} {template.mealCount === 1 ? "хранене" : "хранения"}</span></div><button type="button" disabled={pending} onClick={() => apply(template.id, template.name)}>Приложи</button></article>)}</div> : <p className={styles.templateEmpty}>Нямаш шаблони. Подреди деня и го запази за повторна употреба.</p>}</section>
    <Link className={styles.shoppingCard} href="/shopping-list"><span aria-hidden="true">▤</span><span><strong>Пазарски списък</strong><small>{plannedProducts ? `${plannedProducts} продукта от днешния план` : "Добави хранения, за да подготвиш списъка"}</small></span><b aria-hidden="true">›</b></Link>
    {showTemplateSave ? <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) setShowTemplateSave(false); }}><section className={styles.templateDialog} role="dialog" aria-modal="true" aria-labelledby="template-title"><header><div><p className="life-kicker">Нов шаблон</p><h2 id="template-title">Запази дневния план</h2></div><button className={styles.close} type="button" onClick={() => setShowTemplateSave(false)} aria-label="Затвори">×</button></header><p>Шаблонът запазва храненията, часовете, продуктите, количествата и рецептите. После можеш да го приложиш към всеки ден.</p><div className={styles.templateSummary}><strong>{reusableMeals.length} подробни хранения</strong><span>{reusableMeals.map((meal) => meal.name).join(" · ") || "Няма хранения с отделни продукти или рецепти."}</span></div>{data.meals.length > reusableMeals.length ? <p className={styles.templateNotice}>{data.meals.length - reusableMeals.length} AI/снимкови {data.meals.length - reusableMeals.length === 1 ? "запис няма" : "записа нямат"} отделни продукти и няма да бъдат включени. Отвори храненето и добави продуктите му, за да стане използваемо в шаблон.</p> : null}<label>Име на шаблона<input autoFocus value={templateName} onChange={(event) => setTemplateName(event.target.value)} placeholder="Напр. Високопротеинов тренировъчен ден" maxLength={100}/></label><button className="primary-button" type="button" disabled={pending || !templateName.trim() || !reusableMeals.length} onClick={saveTemplate}>{pending ? "Запазване…" : "Запази шаблона"}</button></section></div> : null}
    {draft ? <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) setDraft(null); }}><section className={styles.editor} role="dialog" aria-modal="true" aria-label="Редактиране на хранене"><header><div><p className="life-kicker">Хранене за деня</p><h2>{draft.name || "Ново хранене"}</h2></div><button className={styles.close} type="button" onClick={() => setDraft(null)} aria-label="Затвори">×</button></header><div className={styles.fields}><label>Име<input value={draft.name} maxLength={100} placeholder="Закуска, обяд…" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Час<input type="time" value={draft.plannedTime} onChange={(event) => setDraft({ ...draft, plannedTime: event.target.value })} /></label></div><section className={styles.draftItems}><header><h3>Храни и рецепти</h3><button type="button" disabled={!choices.length} onClick={addItem}>+ Добави</button></header>{draft.items.map((item, index) => <div className={styles.draftItem} key={item.id}><label>Тип<select value={item.itemType} onChange={(event) => { const type = event.target.value as "product" | "recipe"; const first = choices.find((choice) => choice.type === type); updateItem(index, { itemType: type, referenceId: first?.id ?? "", quantity: type === "product" ? 100 : 1 }); }}><option value="product">Продукт</option><option value="recipe">Рецепта</option></select></label><label>Избор<select value={item.referenceId} onChange={(event) => updateItem(index, { referenceId: event.target.value })}>{choices.filter((choice) => choice.type === item.itemType).map((choice) => <option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label><label>{item.itemType === "product" ? "Грамове" : "Порции"}<input type="number" min="0.01" step={item.itemType === "product" ? ".1" : ".5"} value={item.quantity} onChange={(event) => updateItem(index, { quantity: Math.max(.01, Number(event.target.value) || .01) })} /></label><button type="button" aria-label="Премахни храната" onClick={() => setDraft({ ...draft, items: draft.items.filter((_, itemIndex) => itemIndex !== index) })}>×</button></div>)}</section><footer><button className="primary-button" type="button" disabled={pending || !draft.name.trim() || !draft.items.length} onClick={persist}>{pending ? "Запазване…" : "Запази храненето"}</button></footer></section></div> : null}
  </section>;
}


