"use client";

import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { applyMealTemplate, deleteDynamicMeal, saveDayAsTemplate, saveDynamicMeal } from "../dynamic-actions";
import { mealTotals, type DynamicMeal, type DynamicMealDraft, type DynamicMealDraftItem, type DynamicNutritionData } from "../dynamic-types";
import styles from "./dynamic-nutrition.module.css";

const round = (value: number) => Math.round(value * 10) / 10;
const dateShift = (date: string, days: number) => { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); };
const emptyMeal = (date: string): DynamicMealDraft => ({ id: crypto.randomUUID(), date, name: "", plannedTime: "", items: [] });

export function DynamicNutritionPlanner({ date, data, openNew = false }: { date: string; data: DynamicNutritionData; openNew?: boolean }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [draft, setDraft] = useState<DynamicMealDraft | null>(() => openNew ? emptyMeal(date) : null); const [message, setMessage] = useState("");
  const [templateId, setTemplateId] = useState(data.templates[0]?.id ?? ""); const [templateName, setTemplateName] = useState("");
  const choices = useMemo(() => [...data.products.map((item) => ({ type: "product" as const, id: item.id, label: item.name })), ...data.recipes.map((item) => ({ type: "recipe" as const, id: item.id, label: `Рецепта: ${item.name}` }))], [data.products, data.recipes]);
  const totals = data.meals.reduce((sum, meal) => { const value = mealTotals(meal); sum.calories += value.calories; sum.protein += value.protein; sum.carbs += value.carbs; sum.fat += value.fat; return sum; }, { calories: 0, protein: 0, carbs: 0, fat: 0 });
  const openMeal = (meal?: DynamicMeal) => setDraft(meal ? { id: meal.id, date, name: meal.name, plannedTime: meal.plannedTime ?? "", items: meal.items.map((item) => ({ id: item.id, itemType: item.itemType, referenceId: item.productId ?? item.recipeId ?? "", quantity: item.quantity })) } : emptyMeal(date));
  const addItem = () => setDraft((current) => current && choices.length ? { ...current, items: [...current.items, { id: crypto.randomUUID(), itemType: choices[0].type, referenceId: choices[0].id, quantity: choices[0].type === "product" ? 100 : 1 }] } : current);
  const updateItem = (index: number, patch: Partial<DynamicMealDraftItem>) => setDraft((current) => current ? { ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) } : current);
  const run = (action: () => Promise<{ ok: boolean; message: string }>, close = false) => startTransition(async () => { setMessage("Запазване…"); const result = await action(); setMessage(result.message); if (result.ok) { if (close) setDraft(null); router.refresh(); } });
  const persist = () => draft && run(async () => saveDynamicMeal(draft), true);
  const remove = (meal: DynamicMeal) => { if (window.confirm(`Да изтрия ли „${meal.name}“?`)) run(() => deleteDynamicMeal(meal.id)); };
  const apply = () => { if (!templateId) return; if (window.confirm("Шаблонът ще замени храненията за този ден. Да продължа ли?")) run(() => applyMealTemplate(templateId, date)); };
  const saveTemplate = () => run(async () => { const result = await saveDayAsTemplate(date, templateName); if (result.ok) setTemplateName(""); return result; });

  return <section className={styles.planner}>
    <div className={styles.toolbar}><div><p className="life-kicker">Дневен план</p><h2>{new Date(`${date}T00:00:00Z`).toLocaleDateString("bg-BG", { weekday: "long", day: "numeric", month: "long", timeZone: "UTC" })}</h2></div><button className="primary-button" type="button" onClick={() => openMeal()}>+ Хранене</button></div>
    <nav className={styles.dateNav} aria-label="Смяна на ден"><Link href={`/nutrition?date=${dateShift(date, -1)}`} aria-label="Предишен ден">‹</Link><strong>{date}</strong><Link href={`/nutrition?date=${dateShift(date, 1)}`} aria-label="Следващ ден">›</Link></nav>
    <div className={styles.summary}><span><b>{round(totals.calories)}</b>kcal</span><span><b>{round(totals.protein)}</b>протеин</span><span><b>{round(totals.carbs)}</b>въглех.</span><span><b>{round(totals.fat)}</b>мазнини</span></div>
    <div className={styles.templateBar}><select value={templateId} onChange={(event) => setTemplateId(event.target.value)} aria-label="Хранителен шаблон"><option value="">Избери шаблон</option>{data.templates.map((template) => <option key={template.id} value={template.id}>{template.name} · {template.mealCount} хранения</option>)}</select><button type="button" disabled={pending || !templateId} onClick={apply}>Приложи</button><input value={templateName} onChange={(event) => setTemplateName(event.target.value)} placeholder="Име за нов шаблон" maxLength={100} /><button type="button" disabled={pending || !templateName.trim()} onClick={saveTemplate}>Запази деня като шаблон</button></div>
    {message ? <p className={styles.message} role="status">{message}</p> : null}
    <div className={styles.list}>{data.meals.map((meal) => { const value = mealTotals(meal); const captured = meal.legacyPayload?.source === "food_photo"; const legacyDescription = typeof meal.legacyPayload?.description === "string" ? meal.legacyPayload.description : ""; return <article className={`${styles.meal} ${meal.legacyPayload ? styles.legacy : ""}`} key={meal.id}><header><div><h2>{meal.name}</h2><span>{meal.plannedTime || (captured ? "Добавено от снимка" : "Без час")}</span></div><b>{round(value.calories)} kcal</b></header>{meal.legacyPayload ? <p>{captured ? legacyDescription || "Храна, разпозната от снимка." : "Legacy менюто е запазено като snapshot. Можеш да го замениш с динамично хранене или шаблон, без старият запис да бъде изтрит."}</p> : <div className={styles.items}>{meal.items.map((item) => <div className={styles.item} key={item.id}><span><b>{item.label}</b><br /><small>{item.quantity} {item.unit}</small></span><b>{round(item.calories)} kcal</b></div>)}</div>}<footer><span>П {round(value.protein)} · В {round(value.carbs)} · М {round(value.fat)}</span><div className={styles.mealActions}>{!meal.legacyPayload ? <button type="button" onClick={() => openMeal(meal)}>Редактирай</button> : null}<button type="button" onClick={() => remove(meal)}>Изтрий</button></div></footer></article>; })}{!data.meals.length ? <div className={styles.empty}>Няма хранения за този ден. Добави хранене или приложи шаблон.</div> : null}</div>
    {draft ? <div className={styles.backdrop} onMouseDown={(event) => { if (event.target === event.currentTarget) setDraft(null); }}><section className={styles.editor} role="dialog" aria-modal="true" aria-label="Редактиране на хранене"><header><div><p className="life-kicker">Хранене за деня</p><h2>{draft.name || "Ново хранене"}</h2></div><button className={styles.close} type="button" onClick={() => setDraft(null)} aria-label="Затвори">×</button></header><div className={styles.fields}><label>Име<input value={draft.name} maxLength={100} placeholder="Закуска, обяд…" onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Час<input type="time" value={draft.plannedTime} onChange={(event) => setDraft({ ...draft, plannedTime: event.target.value })} /></label></div><section className={styles.draftItems}><header><h3>Храни и рецепти</h3><button type="button" disabled={!choices.length} onClick={addItem}>+ Добави</button></header>{draft.items.map((item, index) => <div className={styles.draftItem} key={item.id}><label>Тип<select value={item.itemType} onChange={(event) => { const type = event.target.value as "product" | "recipe"; const first = choices.find((choice) => choice.type === type); updateItem(index, { itemType: type, referenceId: first?.id ?? "", quantity: type === "product" ? 100 : 1 }); }}><option value="product">Продукт</option><option value="recipe">Рецепта</option></select></label><label>Избор<select value={item.referenceId} onChange={(event) => updateItem(index, { referenceId: event.target.value })}>{choices.filter((choice) => choice.type === item.itemType).map((choice) => <option key={choice.id} value={choice.id}>{choice.label}</option>)}</select></label><label>{item.itemType === "product" ? "Грамове" : "Порции"}<input type="number" min="0.01" step={item.itemType === "product" ? ".1" : ".5"} value={item.quantity} onChange={(event) => updateItem(index, { quantity: Math.max(.01, Number(event.target.value) || .01) })} /></label><button type="button" aria-label="Премахни храната" onClick={() => setDraft({ ...draft, items: draft.items.filter((_, itemIndex) => itemIndex !== index) })}>×</button></div>)}</section><footer><button className="primary-button" type="button" disabled={pending || !draft.name.trim() || !draft.items.length} onClick={persist}>{pending ? "Запазване…" : "Запази храненето"}</button></footer></section></div> : null}
  </section>;
}


