"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { saveCapturedMeal } from "../dynamic-actions";
import styles from "./food-capture-flow.module.css";
type FoodItem={id:string;name:string;grams:number;calories100g:number;protein100g:number;carbs100g:number;fat100g:number};
type Analysis={name:string;description:string;items:FoodItem[];confidence?:number};
type Props={image:string;date:string;onClose:()=>void;onRetake:()=>void;onImport:()=>void};
const num=(v:unknown)=>Math.max(0,Number(v)||0);const round=(v:number)=>Math.round(v*10)/10;
const emptyItem=():FoodItem=>({id:crypto.randomUUID(),name:"Нов продукт",grams:100,calories100g:0,protein100g:0,carbs100g:0,fat100g:0});
const currentTime=()=>new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Sofia",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date());
export function FoodCaptureFlow({image,date,onClose,onRetake,onImport}:Props){
 const router=useRouter();const [stage,setStage]=useState<"preview"|"analyzing"|"review"|"saving"|"done">("preview");const [view,setView]=useState<"summary"|"details">("summary");const [addOpen,setAddOpen]=useState(false);const [expanded,setExpanded]=useState<string|null>(null);const [note,setNote]=useState("");const [logDate,setLogDate]=useState(date);const [logTime,setLogTime]=useState(currentTime);const [analysis,setAnalysis]=useState<Analysis>({name:"",description:"",items:[]});const [message,setMessage]=useState("");
 const totals=useMemo(()=>analysis.items.reduce((s,i)=>{const f=i.grams/100;return{calories:s.calories+i.calories100g*f,protein:s.protein+i.protein100g*f,carbs:s.carbs+i.carbs100g*f,fat:s.fat+i.fat100g*f};},{calories:0,protein:0,carbs:0,fat:0}),[analysis.items]);
 useEffect(()=>{const p=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=p};},[]);
 const analyze=async()=>{setStage("analyzing");setMessage("");try{const response=await fetch("/api/nutrition/analyze-photo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image,description:note})});const payload=await response.json() as {analysis?:{name?:string;description?:string;items?:Array<Partial<Omit<FoodItem,"id">>>;confidence?:number};error?:string};if(!response.ok||!payload.analysis)throw new Error(payload.error||"Храната не можа да бъде анализирана.");const items=(payload.analysis.items??[]).slice(0,20).map(i=>({id:crypto.randomUUID(),name:String(i.name||"Продукт"),grams:num(i.grams)||100,calories100g:num(i.calories100g),protein100g:num(i.protein100g),carbs100g:num(i.carbs100g),fat100g:num(i.fat100g)}));setAnalysis({name:String(payload.analysis.name||"Хранене"),description:String(payload.analysis.description||note),items:items.length?items:[emptyItem()],confidence:num(payload.analysis.confidence)});setStage("review");}catch(e){setMessage(e instanceof Error?e.message:"Храната не можа да бъде анализирана.");setStage("preview");}};
 const save=async()=>{setStage("saving");setMessage("");const items=analysis.items.map(i=>{const f=i.grams/100;return{name:i.name,grams:i.grams,calories:i.calories100g*f,protein:i.protein100g*f,carbs:i.carbs100g*f,fat:i.fat100g*f};});const result=await saveCapturedMeal({date:logDate,loggedAt:new Date(`${logDate}T${logTime}:00`).toISOString(),name:analysis.name,description:analysis.description||note,...totals,items});if(!result.ok){setMessage(result.message);setStage("review");return;}setStage("done");router.refresh();};
 const update=(id:string,field:keyof Omit<FoodItem,"id">,value:string)=>setAnalysis(c=>({...c,items:c.items.map(i=>i.id===id?{...i,[field]:field==="name"?value:num(value)}:i)}));
 const macro=(label:string,value:number,unit="g")=><span><b>{round(value)}</b> {unit}<small>{label}</small></span>;
 return <div className={styles.backdrop} role="dialog" aria-modal="true"><section className={styles.sheet}>
  <header><button type="button" onClick={view==="details"?()=>setView("summary"):onClose} aria-label={view==="details"?"Назад":"Затвори"}>{view==="details"?"‹":"×"}</button><h1>{view==="details"?"Редакция на ястието":stage==="review"||stage==="saving"?"Добави храна":stage==="done"?"Готово":"Снимай храна"}</h1>{stage==="review"&&view==="summary"?<button type="button" className={styles.headerAdd} onClick={()=>setAddOpen(v=>!v)} aria-label="Опции за добавяне">+</button>:<span/>}</header>
  {addOpen?<div className={styles.addMenu}><div><button type="button" onClick={onRetake}><b>▣</b>Capture</button><button type="button" onClick={onImport}><b>▧</b>Import</button><Link href="/products?mode=scan"><b>⌗</b>Scan</Link></div><button type="button" onClick={()=>{setAddOpen(false);setView("details")}}>AI　Опиши храна</button><Link href="/products">⌕　Търси храна</Link><Link href={`/nutrition?date=${logDate}`}>▤　Хранителен дневник</Link></div>:null}
  {stage==="preview"?<div className={styles.preview}><div className={styles.photo}><Image src={image} alt="Снимана храна" fill unoptimized sizes="100vw"/></div><div className={styles.copy}><h2>Какво хапваш?</h2><p>Добави описание, ако нещо не се вижда ясно.</p></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Напр. две яйца, салата и една филия…" autoFocus/>{message?<p className={styles.error}>{message}</p>:null}<div className={styles.actions}><button className={styles.secondary} onClick={onRetake}>Снимай отново</button><button className={styles.primary} onClick={()=>void analyze()}>Продължи</button></div></div>:null}
  {stage==="analyzing"?<div className={styles.loading}><Image src="/images/pegas-friend.png" alt="" width={118} height={88}/><i/><h2>Pegas анализира ястието…</h2><p>Създавам едно ястие и разпознавам продуктите в него.</p></div>:null}
  {(stage==="review"||stage==="saving")&&view==="summary"?<div className={styles.logSummary}>
   <div className={styles.photoRow}><div><Image src={image} alt="Снимана храна" fill unoptimized sizes="150px"/></div><button type="button" onClick={onRetake}>▣<small>Нова снимка</small></button></div>
   <button type="button" className={styles.mealCard} onClick={()=>setView("details")}><span className={styles.foodEmoji}>🍽️</span><span><strong>{analysis.name}</strong><small>AI разпознато · {round(totals.calories)} kcal</small><em>1 порция　›</em></span></button>
   <button type="button" className={styles.macroSummary} onClick={()=>setView("details")}><span><b>{round(totals.calories)}</b> kcal</span><span>П {round(totals.protein)} g</span><span>В {round(totals.carbs)} g</span><span>М {round(totals.fat)} g</span><i>›</i></button>
   <div className={styles.dateCard}><span>▦</span><label>Дата<input type="date" value={logDate} onChange={e=>setLogDate(e.target.value)}/></label><label>Час<input type="time" value={logTime} onChange={e=>setLogTime(e.target.value)}/></label></div>
   {message?<p className={styles.error}>{message}</p>:null}<button className={styles.primary} disabled={stage==="saving"} onClick={()=>void save()}>{stage==="saving"?"Запазване…":"Добави в дневника"}</button>
  </div>:null}
  {(stage==="review"||stage==="saving")&&view==="details"?<div className={styles.detailsView}><div className={styles.detailHero}><div><Image src={image} alt="" fill unoptimized sizes="92px"/></div><input value={analysis.name} onChange={e=>setAnalysis(c=>({...c,name:e.target.value}))}/><small>1 порция</small></div><div className={styles.detailMacros}>{macro("Калории",totals.calories,"kcal")}{macro("Мазнини",totals.fat)}{macro("Въглех.",totals.carbs)}{macro("Протеин",totals.protein)}</div><div className={styles.itemsHeader}><div><strong>Продукти</strong><small>За една порция</small></div><button onClick={()=>setAnalysis(c=>({...c,items:[...c.items,emptyItem()]}))}>+</button></div><div className={styles.foodItems}>{analysis.items.map(item=><article key={item.id} className={styles.ingredientCard}><button className={styles.ingredientMain} onClick={()=>setExpanded(v=>v===item.id?null:item.id)}><span>🥣</span><span><strong>{item.name}</strong><small>{round(item.grams)} g · {round(item.calories100g*item.grams/100)} kcal</small></span><b>›</b></button>{expanded===item.id?<div className={styles.ingredientEditor}><label>Име<input value={item.name} onChange={e=>update(item.id,"name",e.target.value)}/></label><label>Грамаж<input type="number" value={item.grams} onChange={e=>update(item.id,"grams",e.target.value)}/></label><details><summary>Стойности за 100 g</summary><div><label>kcal<input type="number" value={item.calories100g} onChange={e=>update(item.id,"calories100g",e.target.value)}/></label><label>Протеин<input type="number" value={item.protein100g} onChange={e=>update(item.id,"protein100g",e.target.value)}/></label><label>Въглех.<input type="number" value={item.carbs100g} onChange={e=>update(item.id,"carbs100g",e.target.value)}/></label><label>Мазнини<input type="number" value={item.fat100g} onChange={e=>update(item.id,"fat100g",e.target.value)}/></label></div></details><button className={styles.removeIngredient} onClick={()=>setAnalysis(c=>({...c,items:c.items.filter(i=>i.id!==item.id)}))}>Премахни продукта</button></div>:null}</article>)}</div><button className={styles.primary} onClick={()=>setView("summary")}>Запази промените</button></div>:null}
  {stage==="done"?<div className={styles.done}><span>✓</span><h2>Храната е добавена</h2><p>Ястието и всички продукти са записани в дневника.</p><button className={styles.primary} onClick={onClose}>Готово</button></div>:null}
 </section></div>;
}

