"use client";
import Image from "next/image";
import { useEffect,useMemo,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { saveCapturedMeal } from "../dynamic-actions";
import styles from "./food-capture-flow.module.css";
type FoodUnit="g"|"ml"|"piece"|"serving";
type FoodItem={id:string;name:string;grams:number;unit:FoodUnit;calories100g:number;protein100g:number;carbs100g:number;fat100g:number};
type Analysis={name:string;description:string;items:FoodItem[];confidence?:number};
type SearchProduct={id:string;name:string;brand?:string;servingGrams?:number;calories100g?:number;protein100g?:number;carbs100g?:number;fat100g?:number;favorite?:boolean;source?:string};
type Props={image:string;date:string;onClose:()=>void;onRetake:()=>void;onImport:()=>void};
const num=(v:unknown)=>Math.max(0,Number(v)||0);const round=(v:number)=>Math.round(v*10)/10;
const emptyItem=():FoodItem=>({id:crypto.randomUUID(),name:"Нов продукт",grams:100,unit:"g",calories100g:0,protein100g:0,carbs100g:0,fat100g:0});
const unitLabel=(unit:FoodUnit)=>unit==="piece"?"бр.":unit==="serving"?"порция":unit;
const currentTime=()=>new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/Sofia",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date());
async function createBarcodeReader(){const [{BrowserMultiFormatReader},{BarcodeFormat,DecodeHintType}]=await Promise.all([import("@zxing/browser"),import("@zxing/library")]);const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128]);hints.set(DecodeHintType.TRY_HARDER,true);return new BrowserMultiFormatReader(hints,{delayBetweenScanAttempts:100,delayBetweenScanSuccess:500});}
export function FoodCaptureFlow({image,date,onClose,onRetake,onImport}:Props){
 const router=useRouter();const [stage,setStage]=useState<"preview"|"analyzing"|"review"|"saving"|"done">("preview");const [view,setView]=useState<"summary"|"details">("summary");const [addOpen,setAddOpen]=useState(false);const [describeOpen,setDescribeOpen]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [scannerOpen,setScannerOpen]=useState(false);const [scannerStatus,setScannerStatus]=useState("Насочи камерата към баркода.");const [libraryOpen,setLibraryOpen]=useState(false);const [libraryTab,setLibraryTab]=useState<"search"|"mine">("search");const [libraryFoods,setLibraryFoods]=useState<SearchProduct[]>([]);const [selectedFoods,setSelectedFoods]=useState<SearchProduct[]>([]);const [searchQuery,setSearchQuery]=useState("");const [searchResults,setSearchResults]=useState<SearchProduct[]>([]);const [searchBusy,setSearchBusy]=useState(false);const [searchMessage,setSearchMessage]=useState("");const [expanded,setExpanded]=useState<string|null>(null);const [note,setNote]=useState("");const [logDate,setLogDate]=useState(date);const [logTime,setLogTime]=useState(currentTime);const [analysis,setAnalysis]=useState<Analysis>({name:"",description:"",items:[]});const [message,setMessage]=useState("");const videoRef=useRef<HTMLVideoElement>(null);const detectedRef=useRef(false);
 const [standaloneItems,setStandaloneItems]=useState<FoodItem[]>([]);
 const [openStandalone,setOpenStandalone]=useState<string|null>(null);
 const totals=useMemo(()=>analysis.items.reduce((s,i)=>{const f=i.grams/100;return{calories:s.calories+i.calories100g*f,protein:s.protein+i.protein100g*f,carbs:s.carbs+i.carbs100g*f,fat:s.fat+i.fat100g*f};},{calories:0,protein:0,carbs:0,fat:0}),[analysis.items]);
 const standaloneTotals=useMemo(()=>standaloneItems.reduce((s,i)=>{const f=i.grams/100;return{calories:s.calories+i.calories100g*f,protein:s.protein+i.protein100g*f,carbs:s.carbs+i.carbs100g*f,fat:s.fat+i.fat100g*f};},{calories:0,protein:0,carbs:0,fat:0}),[standaloneItems]);
 const combinedTotals={calories:totals.calories+standaloneTotals.calories,protein:totals.protein+standaloneTotals.protein,carbs:totals.carbs+standaloneTotals.carbs,fat:totals.fat+standaloneTotals.fat};
 useEffect(()=>{const p=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=p};},[]);
 const analyze=async()=>{setDescribeOpen(false);setAddOpen(false);setStage("analyzing");setMessage("");try{const response=await fetch("/api/nutrition/analyze-photo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image,description:note})});const payload=await response.json() as {analysis?:{name?:string;description?:string;items?:Array<Partial<Omit<FoodItem,"id">>>;confidence?:number};error?:string};if(!response.ok||!payload.analysis)throw new Error(payload.error||"Храната не можа да бъде анализирана.");const items=(payload.analysis.items??[]).slice(0,20).map(i=>({id:crypto.randomUUID(),name:String(i.name||"Продукт"),grams:num(i.grams)||100,unit:(["g","ml","piece","serving"].includes(String(i.unit))?i.unit:"g") as FoodUnit,calories100g:num(i.calories100g),protein100g:num(i.protein100g),carbs100g:num(i.carbs100g),fat100g:num(i.fat100g)}));setAnalysis({name:String(payload.analysis.name||"Хранене"),description:String(payload.analysis.description||note),items:items.length?items:[emptyItem()],confidence:num(payload.analysis.confidence)});setView("summary");setStage("review");}catch(e){setMessage(e instanceof Error?e.message:"Храната не можа да бъде анализирана.");setStage(analysis.items.length?"review":"preview");}};
 const save=async()=>{setStage("saving");setMessage("");const loggedAt=new Date(`${logDate}T${logTime}:00`).toISOString();const items=analysis.items.map(i=>{const f=i.grams/100;return{name:i.name,grams:i.grams,unit:i.unit,calories:i.calories100g*f,protein:i.protein100g*f,carbs:i.carbs100g*f,fat:i.fat100g*f};});const primaryName=analysis.items.length===1?analysis.items[0].name:analysis.name;const result=await saveCapturedMeal({date:logDate,loggedAt,name:primaryName,description:analysis.description||note,...totals,items});if(!result.ok){setMessage(result.message);setStage("review");return;}for(const item of standaloneItems){const factor=item.grams/100;const nutrition={calories:item.calories100g*factor,protein:item.protein100g*factor,carbs:item.carbs100g*factor,fat:item.fat100g*factor};const extra=await saveCapturedMeal({date:logDate,loggedAt,name:item.name,description:"Добавено отделно",...nutrition,items:[{name:item.name,grams:item.grams,unit:item.unit,...nutrition}]});if(!extra.ok){setMessage(extra.message);setStage("review");return;}}setStage("done");router.refresh();};
 const update=(id:string,field:keyof Omit<FoodItem,"id">,value:string)=>setAnalysis(c=>({...c,items:c.items.map(i=>i.id===id?{...i,[field]:field==="name"||field==="unit"?value:num(value)}:i)}));
 const searchFood=async()=>{if(!searchQuery.trim())return;setSearchBusy(true);setSearchMessage("");try{const response=await fetch("/api/products/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:searchQuery.trim(),barcode:""})});const payload=await response.json() as {products?:SearchProduct[];error?:string};setSearchResults(payload.products??[]);setSearchMessage(payload.error??(payload.products?.length?"Избери продукт, за да го добавиш.":"Не е намерен продукт."));}catch{setSearchMessage("Търсенето не успя. Опитай отново.");}setSearchBusy(false);};
 const addSearchProduct=(product:SearchProduct)=>{const item:FoodItem={id:crypto.randomUUID(),name:[product.name,product.brand].filter(Boolean).join(" · "),grams:num(product.servingGrams)||100,unit:"g",calories100g:num(product.calories100g),protein100g:num(product.protein100g),carbs100g:num(product.carbs100g),fat100g:num(product.fat100g)};setStandaloneItems(current=>[...current,item]);setSearchOpen(false);setSearchQuery("");setSearchResults([]);setView("summary");};
 const openLibrary=async()=>{setAddOpen(false);setLibraryOpen(true);setSearchMessage("Зареждане…");try{const response=await fetch("/api/nutrition/food-library");const payload=await response.json() as {foods?:SearchProduct[];error?:string};setLibraryFoods(payload.foods??[]);setSearchMessage(payload.error??"");}catch{setSearchMessage("Храните не могат да бъдат заредени.");}};
 const toggleFood=(food:SearchProduct)=>setSelectedFoods(current=>current.some(item=>item.id===food.id)?current.filter(item=>item.id!==food.id):[...current,food]);
 const addSelectedFoods=()=>{const items=selectedFoods.map(food=>({id:crypto.randomUUID(),name:[food.name,food.brand].filter(Boolean).join(" · "),grams:num(food.servingGrams)||100,unit:"g" as FoodUnit,calories100g:num(food.calories100g),protein100g:num(food.protein100g),carbs100g:num(food.carbs100g),fat100g:num(food.fat100g)}));setStandaloneItems(current=>[...current,...items]);setSelectedFoods([]);setLibraryOpen(false);setView("summary");};
 useEffect(()=>{if(!scannerOpen||!videoRef.current)return;detectedRef.current=false;setScannerStatus("Насочи камерата към баркода.");let stop:(()=>void)|undefined;void createBarcodeReader().then(async reader=>{const controls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}}},videoRef.current!,result=>{const barcode=result?.getText().replace(/\D/g,"")??"";if(detectedRef.current||barcode.length<8)return;detectedRef.current=true;setScannerStatus(`Разпознат ${barcode}. Търся продукта…`);void fetch("/api/products/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:"",barcode})}).then(response=>response.json()).then((payload:{products?:SearchProduct[];error?:string})=>{const product=payload.products?.[0];if(product){addSearchProduct(product);setScannerOpen(false);}else{detectedRef.current=false;setScannerStatus(payload.error||"Продуктът не е намерен. Опитай отново или използвай Търсене.");}}).catch(()=>{detectedRef.current=false;setScannerStatus("Продуктът не можа да бъде потърсен.");});});stop=()=>controls.stop();}).catch(error=>{setScannerStatus(error instanceof Error&&error.name==="NotAllowedError"?"Разреши достъп до камерата от настройките на Safari.":"Камерата не можа да бъде стартирана.");});return()=>stop?.();},[scannerOpen]);
 const editingItem=analysis.items.find(item=>item.id===expanded)??null;
 const macro=(label:string,value:number,unit="g")=><span><b>{round(value)}</b> {unit}<small>{label}</small></span>;
 return <div className={styles.backdrop} role="dialog" aria-modal="true"><section className={styles.sheet}>
  <header><button type="button" onClick={view==="details"?()=>setView("summary"):onClose} aria-label={view==="details"?"Назад":"Затвори"}>{view==="details"?"‹":"×"}</button><h1>{view==="details"?"Редакция на ястието":stage==="review"||stage==="saving"?"Добави храна":stage==="done"?"Готово":"Снимай храна"}</h1>{stage==="review"&&view==="summary"?<button type="button" className={styles.headerAdd} onClick={()=>setAddOpen(v=>!v)} aria-label="Опции за добавяне">+</button>:<span/>}</header>
  {addOpen?<div className={styles.addMenu}><div><button type="button" onClick={onRetake}><b>▣</b>Capture</button><button type="button" onClick={onImport}><b>▧</b>Import</button><button type="button" onClick={()=>{setAddOpen(false);setScannerOpen(true)}}><b>⌗</b>Scan</button></div><button type="button" onClick={()=>{setAddOpen(false);setNote(analysis.description||note);setDescribeOpen(true)}}>AI　Опиши храна</button><button type="button" onClick={()=>{setAddOpen(false);setSearchOpen(true)}}>⌕　Търси храна</button><button type="button" onClick={()=>void openLibrary()}>▤　Хранителен дневник</button></div>:null}
  {scannerOpen?<div className={styles.scannerBackdrop}><section className={styles.scannerSheet}><header><div><small>Баркод скенер</small><h2>Сканирай продукт</h2></div><button type="button" onClick={()=>setScannerOpen(false)}>×</button></header><div className={styles.scannerVideo}><video ref={videoRef} muted playsInline/><span/></div><p>{scannerStatus}</p><button type="button" className={styles.secondary} onClick={()=>setScannerOpen(false)}>Затвори</button></section></div>:null}
  {describeOpen?<div className={styles.describeBackdrop} onClick={()=>setDescribeOpen(false)}><section className={styles.describeSheet} onClick={event=>event.stopPropagation()}><header><div><small>AI описание</small><h2>Какво има в ястието?</h2></div><button type="button" onClick={()=>setDescribeOpen(false)}>×</button></header><p>Опиши продуктите, количествата или начина на приготвяне. Pegas ще анализира снимката отново с тази информация.</p><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Напр. 3 яйца, 80 g пилешко и една тортила…" autoFocus/><div><button type="button" className={styles.secondary} onClick={()=>setDescribeOpen(false)}>Отказ</button><button type="button" className={styles.primary} disabled={!note.trim()} onClick={()=>void analyze()}>Анализирай</button></div></section></div>:null}
  {searchOpen?<div className={styles.describeBackdrop} onClick={()=>setSearchOpen(false)}><section className={`${styles.describeSheet} ${styles.searchSheet}`} onClick={event=>event.stopPropagation()}><header><div><small>Продуктова база</small><h2>Търси храна</h2></div><button type="button" onClick={()=>setSearchOpen(false)}>×</button></header><div className={styles.searchInput}><input value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")void searchFood()}} placeholder="Име, марка или баркод" autoFocus/><button type="button" onClick={()=>void searchFood()} disabled={searchBusy||!searchQuery.trim()}>{searchBusy?"…":"Търси"}</button></div>{searchMessage?<p className={styles.searchMessage}>{searchMessage}</p>:null}<div className={styles.searchResults}>{searchResults.map(product=><button type="button" key={product.id} onClick={()=>addSearchProduct(product)}><span>🍎</span><span><strong>{product.name}</strong><small>{product.brand||"Без марка"} · {round(num(product.calories100g))} kcal / 100 g</small><b>П {round(num(product.protein100g))} · В {round(num(product.carbs100g))} · М {round(num(product.fat100g))}</b></span><i>+</i></button>)}</div></section></div>:null}
  {libraryOpen?<div className={styles.libraryBackdrop}><section className={styles.librarySheet}><header><button type="button" onClick={()=>{setLibraryOpen(false);setSelectedFoods([])}}>Отказ</button><strong>Хранителен дневник</strong><button type="button" disabled={!selectedFoods.length} onClick={addSelectedFoods}>Добави{selectedFoods.length?` (${selectedFoods.length})`:""}</button></header><nav><button className={libraryTab==="search"?styles.activeTab:""} onClick={()=>setLibraryTab("search")}>Търсене</button><button className={libraryTab==="mine"?styles.activeTab:""} onClick={()=>setLibraryTab("mine")}>Моите храни</button></nav><div className={styles.librarySearch}><span>⌕</span><input value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&libraryTab==="search")void searchFood()}} placeholder="Търси храни и напитки"/>{libraryTab==="search"?<button onClick={()=>void searchFood()} disabled={searchBusy}>Търси</button>:null}</div><div className={styles.selectedBar}>{selectedFoods.length?selectedFoods.map(food=><button key={food.id} onClick={()=>toggleFood(food)}>{food.name} ×</button>):<span>Няма избрани продукти</span>}</div>{libraryTab==="mine"?<div className={styles.libraryFilters}><button className={styles.activeFilter}>Любими</button><button>Персонални</button><button>История</button></div>:null}{searchMessage?<p className={styles.libraryMessage}>{searchMessage}</p>:null}<div className={styles.libraryList}>{(libraryTab==="search"?searchResults:libraryFoods.filter(food=>!searchQuery.trim()||`${food.name} ${food.brand}`.toLocaleLowerCase("bg").includes(searchQuery.toLocaleLowerCase("bg")))).map(food=>{const selected=selectedFoods.some(item=>item.id===food.id);return <button type="button" key={food.id} onClick={()=>toggleFood(food)}><span className={styles.libraryIcon}>{food.favorite?"⭐":"🍎"}</span><span><strong>{food.name}</strong><small>{round(num(food.calories100g)*num(food.servingGrams||100)/100)} kcal · {round(num(food.servingGrams)||100)} g</small>{food.brand?<em>{food.brand}</em>:null}</span><i className={selected?styles.selectedPlus:""}>{selected?"✓":"+"}</i></button>})}</div></section></div>:null}
  {stage==="preview"?<div className={styles.preview}><div className={styles.photo}><Image src={image} alt="Снимана храна" fill unoptimized sizes="100vw"/></div><div className={styles.copy}><h2>Какво хапваш?</h2><p>Добави описание, ако нещо не се вижда ясно.</p></div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Напр. две яйца, салата и една филия…" autoFocus/>{message?<p className={styles.error}>{message}</p>:null}<div className={styles.actions}><button className={styles.secondary} onClick={onRetake}>Снимай отново</button><button className={styles.primary} onClick={()=>void analyze()}>Продължи</button></div></div>:null}
  {stage==="analyzing"?<div className={styles.loading}><Image src="/images/pegas-friend.png" alt="" width={118} height={88}/><i/><h2>Pegas анализира ястието…</h2><p>Създавам едно ястие и разпознавам продуктите в него.</p></div>:null}
  {(stage==="review"||stage==="saving")&&view==="summary"?<div className={styles.logSummary}>
   <div className={styles.photoRow}><div><Image src={image} alt="Снимана храна" fill unoptimized sizes="150px"/></div><button type="button" onClick={onRetake}>▣<small>Нова снимка</small></button></div>
   <button type="button" className={styles.mealCard} onClick={()=>setView("details")}><span className={styles.foodEmoji}>{analysis.items.length===1?"🥣":"🍽️"}</span><span><strong>{analysis.items.length===1?analysis.items[0].name:analysis.name}</strong><small>{analysis.items.length===1?`${round(analysis.items[0].grams)} g`:`${analysis.items.length} продукта`} · {round(totals.calories)} kcal</small><em>1 порция　›</em></span></button>
   {standaloneItems.map(item=><article className={styles.standaloneCard} key={item.id}><span>🍎</span><button type="button" onClick={()=>setOpenStandalone(current=>current===item.id?null:item.id)}><strong>{item.name}</strong><small>{round(item.grams)} g · {round(item.calories100g*item.grams/100)} kcal</small></button><button type="button" onClick={()=>setStandaloneItems(current=>current.filter(entry=>entry.id!==item.id))} aria-label={`Премахни ${item.name}`}>×</button>{openStandalone===item.id?<div className={styles.standaloneEditor}><label>Име<input value={item.name} onChange={event=>setStandaloneItems(current=>current.map(entry=>entry.id===item.id?{...entry,name:event.target.value}:entry))}/></label><label>Грамаж<input type="number" value={item.grams} onChange={event=>setStandaloneItems(current=>current.map(entry=>entry.id===item.id?{...entry,grams:num(event.target.value)}:entry))}/></label><button type="button" onClick={()=>{setAnalysis(current=>({...current,items:[...current.items,item],name:current.items.length?current.name:item.name}));setStandaloneItems(current=>current.filter(entry=>entry.id!==item.id));setOpenStandalone(null);setView("details")}}>Добави към групата</button></div>:null}</article>)}
   <button type="button" className={styles.macroSummary} onClick={()=>setView("details")}><span><b>{round(combinedTotals.calories)}</b> kcal</span><span>П {round(combinedTotals.protein)} g</span><span>В {round(combinedTotals.carbs)} g</span><span>М {round(combinedTotals.fat)} g</span><i>›</i></button>
   <div className={styles.dateCard}><span>▦</span><label>Дата<input type="date" value={logDate} onChange={e=>setLogDate(e.target.value)}/></label><label>Час<input type="time" value={logTime} onChange={e=>setLogTime(e.target.value)}/></label></div>
   {message?<p className={styles.error}>{message}</p>:null}<button className={styles.primary} disabled={stage==="saving"} onClick={()=>void save()}>{stage==="saving"?"Запазване…":"Добави в дневника"}</button>
  </div>:null}
  {(stage==="review"||stage==="saving")&&view==="details"?<div className={styles.detailsView}><div className={styles.detailHero}><div><Image src={image} alt="" fill unoptimized sizes="92px"/></div><input value={analysis.name} onChange={e=>setAnalysis(c=>({...c,name:e.target.value}))}/><small>1 порция</small></div><div className={styles.detailMacros}>{macro("Калории",totals.calories,"kcal")}{macro("Мазнини",totals.fat)}{macro("Въглех.",totals.carbs)}{macro("Протеин",totals.protein)}</div><div className={styles.itemsHeader}><div><strong>Продукти</strong><small>За една порция</small></div><button onClick={()=>setAnalysis(c=>({...c,items:[...c.items,emptyItem()]}))}>+</button></div><div className={styles.foodItems}>{analysis.items.map(item=><article key={item.id} className={styles.ingredientCard}><button className={styles.ingredientMain} onClick={()=>setExpanded(v=>v===item.id?null:item.id)}><span>🥣</span><span><strong>{item.name}</strong><small>{round(item.grams)} g · {round(item.calories100g*item.grams/100)} kcal</small></span><b>›</b></button>{expanded===item.id?<div className={styles.ingredientEditor}><label>Име<input value={item.name} onChange={e=>update(item.id,"name",e.target.value)}/></label><label>Грамаж<input type="number" value={item.grams} onChange={e=>update(item.id,"grams",e.target.value)}/></label><details><summary>Стойности за 100 g</summary><div><label>kcal<input type="number" value={item.calories100g} onChange={e=>update(item.id,"calories100g",e.target.value)}/></label><label>Протеин<input type="number" value={item.protein100g} onChange={e=>update(item.id,"protein100g",e.target.value)}/></label><label>Въглех.<input type="number" value={item.carbs100g} onChange={e=>update(item.id,"carbs100g",e.target.value)}/></label><label>Мазнини<input type="number" value={item.fat100g} onChange={e=>update(item.id,"fat100g",e.target.value)}/></label></div></details><button className={styles.removeIngredient} onClick={()=>setAnalysis(c=>({...c,items:c.items.filter(i=>i.id!==item.id)}))}>Премахни продукта</button></div>:null}</article>)}</div><button className={styles.primary} onClick={()=>setView("summary")}>Запази промените</button></div>:null}
  {(stage==="review"||stage==="saving")&&view==="details"?<div className={styles.groupActions}><button type="button" onClick={onClose}>Премахни групата</button><button type="button" onClick={()=>{setExpanded(null);setView("summary")}}>Запази групата</button></div>:null}
  {editingItem?<div className={styles.ingredientScreen}><header><button type="button" onClick={()=>setExpanded(null)}>‹</button><h2>Редакция на продукт</h2><span/></header><div className={styles.ingredientHero}><span>🥣</span><input value={editingItem.name} onChange={event=>update(editingItem.id,"name",event.target.value)}/></div><div className={styles.ingredientNutrition}>{macro("Калории",editingItem.calories100g*editingItem.grams/100,"kcal")}{macro("Мазнини",editingItem.fat100g*editingItem.grams/100)}{macro("Въглех.",editingItem.carbs100g*editingItem.grams/100)}{macro("Протеин",editingItem.protein100g*editingItem.grams/100)}</div><section className={styles.amountEditor}><h3>Количество</h3><div><input type="number" inputMode="decimal" value={editingItem.grams} onChange={event=>update(editingItem.id,"grams",event.target.value)}/><strong>{unitLabel(editingItem.unit)}</strong><button type="button" onClick={()=>update(editingItem.id,"grams",String(Math.max(0,editingItem.grams-1)))}>−</button><button type="button" onClick={()=>update(editingItem.id,"grams",String(editingItem.grams+1))}>+</button></div><nav>{(["serving","piece","g","ml"] as FoodUnit[]).map(unit=><button type="button" className={editingItem.unit===unit?styles.activeUnit:""} key={unit} onClick={()=>update(editingItem.id,"unit",unit)}>{unitLabel(unit)}</button>)}</nav></section><details className={styles.customNutrition}><summary>Редактирай стойностите за 100 g/ml</summary><div><label>kcal<input type="number" value={editingItem.calories100g} onChange={event=>update(editingItem.id,"calories100g",event.target.value)}/></label><label>Протеин<input type="number" value={editingItem.protein100g} onChange={event=>update(editingItem.id,"protein100g",event.target.value)}/></label><label>Въглех.<input type="number" value={editingItem.carbs100g} onChange={event=>update(editingItem.id,"carbs100g",event.target.value)}/></label><label>Мазнини<input type="number" value={editingItem.fat100g} onChange={event=>update(editingItem.id,"fat100g",event.target.value)}/></label></div></details><div className={styles.ingredientActions}><button type="button" onClick={()=>{setAnalysis(current=>({...current,items:current.items.filter(item=>item.id!==editingItem.id)}));setExpanded(null)}}>Премахни</button><button type="button" onClick={()=>setExpanded(null)}>Запази</button></div></div>:null}
  {stage==="done"?<div className={styles.done}><span>✓</span><h2>Храната е добавена</h2><p>Ястието и всички продукти са записани в дневника.</p><button className={styles.primary} onClick={onClose}>Готово</button></div>:null}
 </section></div>;
}
