import { redirect } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { AppNavigation } from "@/components/app-navigation";
import { createClient } from "@/lib/supabase/server";
import { dietTermsFromMenus, getPromotions, isDietSuitablePromotion, retailerBrochures, type Promotion } from "@/lib/promotions";
import { getMenuLibrary, type MealMenuSettings } from "@/features/nutrition/menu-library";

export const metadata = { title: "Промоции · Дневник на живота" };
const money = (value: number) => new Intl.NumberFormat("bg-BG", { style: "currency", currency: "EUR" }).format(value);
const stores: Promotion["store"][] = ["Kaufland", "Lidl", "Billa", "Fantastico", "T-Market"];

export default async function PromotionsPage({ searchParams }: { searchParams: Promise<{ q?: string; store?: string; view?: string }> }) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const params = await searchParams; const query = String(params.q ?? "").trim().toLocaleLowerCase("bg-BG"); const selectedStore = stores.includes(params.store as Promotion["store"]) ? params.store as Promotion["store"] : ""; const dietView = params.view !== "all";
  const menus = getMenuLibrary(user.user_metadata as MealMenuSettings); const dietTerms = dietTermsFromMenus(menus);
  const offers = (await getPromotions()).filter((offer) => (!dietView || isDietSuitablePromotion(offer, dietTerms)) && (!selectedStore || offer.store === selectedStore) && (!query || offer.name.toLocaleLowerCase("bg-BG").includes(query))).sort((a, b) => (b.oldPrice ? (b.oldPrice - b.price) / b.oldPrice : 0) - (a.oldPrice ? (a.oldPrice - a.price) / a.oldPrice : 0)).slice(0, 240);
  const dietHref = `?${new URLSearchParams({ ...(params.q ? { q: params.q } : {}), ...(selectedStore ? { store: selectedStore } : {}) })}`; const allHref = `?${new URLSearchParams({ view: "all", ...(params.q ? { q: params.q } : {}), ...(selectedStore ? { store: selectedStore } : {}) })}`;
  return <main className="life-app-shell"><AppNavigation active="promotions" /><section className="promotions-page"><header><div><p className="life-kicker">Умен пазар</p><h1>Седмични промоции</h1><p>{dietView ? "Всички актуални предложения, подходящи за хранителния ти режим." : "Всички актуални предложения от наблюдаваните вериги."}</p></div><span>{offers.length} предложения</span></header><nav className="promotion-view-tabs" aria-label="Вид промоции"><Link className={dietView ? "active" : ""} href={dietHref}>Подходящи за режима</Link><Link className={!dietView ? "active" : ""} href={allHref}>Всички оферти</Link></nav><form className="promotion-filters">{!dietView ? <input type="hidden" name="view" value="all" /> : null}<input name="q" defaultValue={params.q ?? ""} placeholder="Търси продукт, марка или разфасовка" /><select name="store" defaultValue={selectedStore}><option value="">Всички магазини</option>{stores.map((store) => <option key={store}>{store}</option>)}</select><button type="submit">Търси</button></form><div className="promotion-brochures">{stores.map((store) => <a key={store} href={retailerBrochures[store]} target="_blank" rel="noreferrer"><b>{store}</b><span>Официална брошура ↗</span></a>)}</div>{offers.length ? <div className="promotion-grid">{offers.map((offer) => { const discount = offer.oldPrice ? Math.round((1 - offer.price / offer.oldPrice) * 100) : 0; return <article key={`${offer.store}-${offer.id}`}><div className="promotion-image">{offer.imageUrl ? <Image src={offer.imageUrl} alt="" width={600} height={400} unoptimized /> : <span>€</span>}{discount > 0 ? <b>-{discount}%</b> : null}</div><div className="promotion-copy"><span>{offer.store}</span><h2>{offer.name}</h2><div><strong>{money(offer.price)}</strong>{offer.oldPrice ? <del>{money(offer.oldPrice)}</del> : null}</div><small>{offer.validFrom ? `От ${offer.validFrom} ` : ""}{offer.validUntil ? `до ${offer.validUntil}` : "Провери валидността"}</small><a href={offer.url || retailerBrochures[offer.store]} target="_blank" rel="noreferrer">Провери офертата ↗</a></div></article>; })}</div> : <div className="promotion-empty"><strong>Няма намерени предложения</strong><p>Провери официалните брошури или опитай с по-кратко име.</p></div>}<p className="promotion-source">Цените се обновяват автоматично през SmartPazar и се показват информационно. Наличността и крайната цена се потвърждават от магазина.</p></section></main>;
}
